#ifndef GUARD_CONSTANTS_RANDOM_MON_GENERATION_H
#define GUARD_CONSTANTS_RANDOM_MON_GENERATION_H

enum
{
    SPECIES_GENERATOR_NO_SUPERMONS,
    SPECIES_GENERATOR_LIMITED_POOL,
    SPECIES_GENERATOR_BST_RESTRICTED,
    SPECIES_GENERATOR_MOM_AFTER_WHITEOUT,
    RANDOM_SPECIES_OPTIONS_COUNT,
};

enum
{
    ITEM_GENERATOR_STANDARD,
    ITEM_GENERATOR_LIMITED_POOL,
    ITEM_GENERATOR_TM_TRADER,
    ITEM_GENERATOR_BALL_TRADER,
    ITEM_GENERATOR_MINT_TRADER,
    ITEM_GENERATOR_HELD_TRADER,
    RANDOM_ITEM_OPTIONS_COUNT,
};

#endif // GUARD_CONSTANTS_RANDOM_MON_GENERATION_H
