#ifndef GUARD_CONSTANTS_RANDOM_MON_GENERATION_H
#define GUARD_CONSTANTS_RANDOM_MON_GENERATION_H

enum
{
    SPECIES_GENERATOR_NO_SUPERMONS,
    SPECIES_GENERATOR_LIMITED_POOL,
    SPECIES_GENERATOR_BST_RESTRICTED,
    SPECIES_GENERATOR_MOM_AFTER_WHITEOUT,
    RANDOM_SPECIES_OPTIONS_COUNT,
};

enum
{
    ITEM_GENERATOR_STANDARD,
    ITEM_GENERATOR_LIMITED_POOL,
    ITEM_GENERATOR_CONSUMABLE,
    ITEM_GENERATOR_TREASURE,
    ITEM_GENERATOR_HELD_ITEM,
    ITEM_GENERATOR_MINT,
    ITEM_GENERATOR_TM,
    ITEM_GENERATOR_TRASH,
    RANDOM_ITEM_OPTIONS_COUNT,
};

#endif // GUARD_CONSTANTS_RANDOM_MON_GENERATION_H
