# 1 "data//maps/OldaleTown_House2/scripts.pory"

# 2 "data//maps/OldaleTown_House2/scripts.pory"
OldaleTown_House2_MapScripts::
# 3 "data//maps/OldaleTown_House2/scripts.pory"
	.byte 0
# 4 "data//maps/OldaleTown_House2/scripts.pory"

# 5 "data//maps/OldaleTown_House2/scripts.pory"
OldaleTown_House2_EventScript_Woman::
# 6 "data//maps/OldaleTown_House2/scripts.pory"
	msgbox OldaleTown_House2_Text_PokemonLevelUp, MSGBOX_NPC
# 7 "data//maps/OldaleTown_House2/scripts.pory"
	end
# 8 "data//maps/OldaleTown_House2/scripts.pory"

# 9 "data//maps/OldaleTown_House2/scripts.pory"
OldaleTown_House2_EventScript_Man::
# 10 "data//maps/OldaleTown_House2/scripts.pory"
	msgbox OldaleTown_House2_Text_YoullGoFurtherWithStrongPokemon, MSGBOX_NPC
# 11 "data//maps/OldaleTown_House2/scripts.pory"
	end
# 12 "data//maps/OldaleTown_House2/scripts.pory"

# 13 "data//maps/OldaleTown_House2/scripts.pory"
OldaleTown_House2_Text_PokemonLevelUp:
# 14 "data//maps/OldaleTown_House2/scripts.pory"
	.string "HOENN doesn't have modern roads,\n"
# 15 "data//maps/OldaleTown_House2/scripts.pory"
	.string "so the area between towns and cities\l"
# 16 "data//maps/OldaleTown_House2/scripts.pory"
	.string "is mostly wilderness.$"
# 17 "data//maps/OldaleTown_House2/scripts.pory"

# 18 "data//maps/OldaleTown_House2/scripts.pory"
OldaleTown_House2_Text_YoullGoFurtherWithStrongPokemon:
# 19 "data//maps/OldaleTown_House2/scripts.pory"
	.string "If the POKéMON with you become\n"
# 20 "data//maps/OldaleTown_House2/scripts.pory"
	.string "stronger, you'll be able to go farther\l"
# 21 "data//maps/OldaleTown_House2/scripts.pory"
	.string "away from here.$"
